version: '3'

services:
  postgres:
    image: 'postgres'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/app'

volumes:
  postgres: